In [1]:
import numpy as np

In [2]:
mesh_vertices = np.load('data/scannet/pointgroup_data/scene0032_00_aligned_vert.npy')

In [3]:
instance_labels = np.load('data/scannet/pointgroup_data/scene0032_00_ins_label_pg.npy')

In [4]:
semantic_labels = np.load('data/scannet/pointgroup_data/scene0032_00_sem_label_pg.npy')

In [18]:
# semantic_labels = np.load('data/scannet/pointgroup_data/scene0032_00_sem_label_pg.npy')
instance_bboxes = np.load('data/scannet/pointgroup_data/scene0032_00_aligned_bbox.npy')

In [19]:
instance_bboxes

array([[-0.87566018, -1.51550663,  0.6914115 ,  1.00516367,  0.07069063,
         1.43334413,  8.        ,  0.        ],
       [-0.85770297,  1.14475381,  1.16841543,  1.2584722 ,  0.33959216,
         0.79028302, 15.        ,  1.        ],
       [-1.54708779, -0.56420749,  1.14068747,  0.13823605,  0.94088638,
         1.43012381,  9.        ,  2.        ],
       [-0.86243367,  0.72458816,  0.3943601 ,  1.25101328,  0.61323756,
         0.80105573, 14.        ,  3.        ],
       [-0.63021553,  0.51570183,  0.41855964,  0.65191638,  0.41261521,
         0.86933702,  5.        ,  5.        ],
       [ 0.83859503,  0.54919207,  0.5429095 ,  2.31049204,  1.51355553,
         1.12715268,  4.        ,  6.        ],
       [ 1.9721055 , -1.36283004,  0.68354529,  0.09441841,  1.00206733,
         1.3692342 ,  8.        ,  7.        ],
       [-1.46833467, -0.58686543,  0.1262002 ,  0.07130694,  1.06326985,
         0.2532655 , 39.        , 10.        ]])

In [6]:
np.unique(semantic_labels)

array([ 0,  4,  5,  8,  9, 14, 39], dtype=uint32)

In [7]:
np.concatenate((np.array([1, 2]), np.array([1, 2, 3]), np.array([0])))

array([1, 2, 1, 2, 3, 0])

In [10]:
np.unique(semantic_labels[instance_labels==1])

array([5], dtype=uint32)

In [14]:
len(instance_bboxes)

8

In [15]:
instance_bboxes[:3, -1]

array([0., 1., 2.])

In [16]:
instance_bboxes.shape

(8, 8)

In [20]:
for i_instance in np.unique(instance_labels):

    # find all points belong to that instance
    ind = np.nonzero(instance_labels == i_instance)[0]
    print(ind)

[    0     2     6 ... 49995 49996 49997]
[  105   253   296 ... 49930 49968 49994]
[    8    23    45 ... 49962 49966 49984]
[   55   140   212   329   455   508   564   605   863   877   882  1529
  1734  1841  1851  2017  2057  2164  2179  2297  2377  2431  2497  2622
  2911  3280  3371  3374  3465  3576  3617  3677  3698  3802  3820  3899
  4111  4188  4569  4624  4655  4822  4856  4931  4955  5028  5076  5140
  5187  5356  5418  5446  5457  5580  5622  5660  5731  5744  5894  5931
  6008  6062  6148  6207  6229  6271  6530  6591  6622  6745  6769  6791
  6814  6878  6959  6963  7037  7165  7295  7336  7421  7549  7610  7633
  7716  7989  8229  8327  8368  8435  8462  8467  8489  8561  8576  8659
  8667  8761  8783  8866  8958  9071  9085  9149  9163  9287  9362  9369
  9413  9425  9501  9557  9577  9660  9686  9734  9775  9872  9977 10007
 10240 10272 10279 10296 10569 10661 10851 10879 11197 11307 11389 11410
 11417 11450 11546 11703 11708 11836 12013 12037 12139 12194 12303 1241