In [1]:
import numpy as np
import os

In [3]:
# scene_id = 'scene0125_00'
scene_id = 'scene0050_00'
PATH = '/home/duccd/Desktop/InstanceRefer/data/scannet/pointgroup_data'
mesh_vertices = np.load(os.path.join(PATH, scene_id) + "_aligned_vert.npy")  # axis-aligned
instance_labels = np.load(os.path.join(PATH, scene_id) + "_ins_label.npy")
semantic_labels = np.load(os.path.join(PATH, scene_id) + "_sem_label_pg.npy")
instance_bboxes = np.load(os.path.join(PATH, scene_id) + "_aligned_bbox.npy")

In [181]:
for i in np.unique(instance_labels):
    indices = np.where(instance_labels == i)[0]
    point = mesh_vertices[indices][:,0:3]
    color = mesh_vertices[indices][:,3:6]/255.0
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(point)
    pcd.colors = o3d.utility.Vector3dVector(color)
    # o3d.io.write_point_cloud("paper_data/pcls/{}.ply".format(i), pcd)
    o3d.visualization.draw_geometries([pcd])

IOStream.flush timed out


In [4]:
import open3d as o3d

# Create a sample point cloud (random points)
points = mesh_vertices[:, 0:3]
pcl_color = mesh_vertices[:, 3:6]/255.0
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)
pcd.colors = o3d.utility.Vector3dVector(pcl_color)

# Define multiple axis-aligned bounding boxes
aabbs = []
id=0
for box in instance_bboxes:
    center = box[0:3].tolist()
    size = box[3:6].tolist()
    min_bound = np.array(center) - np.array(size) / 2
    max_bound = np.array(center) + np.array(size) / 2
    aabb = o3d.geometry.AxisAlignedBoundingBox(min_bound, max_bound)
    aabb.color = (0, 1, 0)  # green
    if id==0:
        aabbs.append(aabb)
    id+= 1
# Visualize point cloud with bounding boxes
o3d.visualization.draw_geometries([pcd])

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [27]:
import json
with open('data/ScanRefer_filtered_val_with_id.json', 'r') as file:
    data = json.load(file)

In [31]:
for i in data:
    if i['scene_id'] == 'scene0050_00' and i['object_name'] == 'door':
        print(i)

{'scene_id': 'scene0050_00', 'object_id': '9', 'object_name': 'door', 'ann_id': '1', 'description': "this door is to the left of another door, with it's doorknob on the left side of the door.  this door is the nearest to the desk which is on the left wall, and the chair in front of it.", 'token': ['this', 'door', 'is', 'to', 'the', 'left', 'of', 'another', 'door', ',', 'with', 'it', "'s", 'doorknob', 'on', 'the', 'left', 'side', 'of', 'the', 'door', '.', 'this', 'door', 'is', 'the', 'nearest', 'to', 'the', 'desk', 'which', 'is', 'on', 'the', 'left', 'wall', ',', 'and', 'the', 'chair', 'in', 'front', 'of', 'it', '.'], 'id': 467}
{'scene_id': 'scene0050_00', 'object_id': '10', 'object_name': 'door', 'ann_id': '1', 'description': 'this is a brown door. it is to the right of another door.', 'token': ['this', 'is', 'a', 'brown', 'door', '.', 'it', 'is', 'to', 'the', 'right', 'of', 'another', 'door', '.'], 'id': 476}
{'scene_id': 'scene0050_00', 'object_id': '9', 'object_name': 'door', 'ann_

In [51]:
scene0047_00
scene0048_00
scene0050_00
scene0053_00

NameError: name 'scene0047_00' is not defined

In [2]:
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [30]:
file = "/home/duccd/Desktop/scannet_download/scans/scene0050_00/scene0050_00_vh_clean_2.ply"
import open3d as o3d

# Load the PLY file
pcd = o3d.io.read_point_cloud(file)

# Print basic info
print(pcd)
print(np.asarray(pcd.points))

# Visualize the point cloud
o3d.visualization.draw_geometries([pcd])

PointCloud with 211406 points.
[[0.94484556 0.76709068 0.16177888]
 [1.04911613 0.79389089 0.15133797]
 [1.0480243  0.78115064 0.15720609]
 ...
 [6.44555712 3.87846947 1.83808398]
 [6.41482258 3.53393269 1.86150002]
 [6.4167037  3.54173875 1.88219833]]
